version: '3'
services:
  pg-db:
    container_name: pg-db
    image: postgres:11.1-alpine
    network_mode: bridge
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: dbtest
    ports:
      - 6000:5432
